import type { AliasSpec } from '../core/aliasTypes'

export const passiveAliases: AliasSpec[] = [
  {
    name: 'Current Sense Resistor',
    anchor: 'Resistor',
    category: 'passives',
    paletteGroup: 'resistors',
    description: 'Low-value resistor for measuring current via voltage drop',
    keywords: ['current sense', 'shunt', 'ams1117', 'ina219'],
  },
  {
    name: 'Ceramic Capacitor',
    anchor: 'Capacitor',
    category: 'passives',
    paletteGroup: 'capacitors',
    description: 'Non-polarized ceramic capacitor for decoupling and filtering',
    keywords: ['ceramic', 'mlcc', 'decouple', '104', 'nf'],
  },
  {
    name: 'Electrolytic Capacitor',
    anchor: 'Capacitor',
    category: 'passives',
    paletteGroup: 'capacitors',
    description: 'Polarized electrolytic capacitor for bulk energy storage',
    keywords: ['electrolytic', 'polarized', 'uf', 'bulk'],
  },
  {
    name: 'Tantalum Capacitor',
    anchor: 'Capacitor',
    category: 'passives',
    paletteGroup: 'capacitors',
    description: 'Polarized tantalum capacitor — compact bulk capacitance',
    keywords: ['tantalum', 'polarized', 'smd'],
  },
  {
    name: 'Polymer Capacitor',
    anchor: 'Capacitor',
    category: 'passives',
    paletteGroup: 'capacitors',
    description: 'Low-ESR polymer aluminum capacitor',
    keywords: ['polymer', 'polarized', 'low esr'],
  },
  {
    name: 'Film Capacitor',
    anchor: 'Capacitor',
    category: 'passives',
    paletteGroup: 'capacitors',
    description: 'Film dielectric capacitor for stable filtering',
    keywords: ['film', 'polyester', 'pp'],
  },
  {
    name: 'Supercapacitor',
    anchor: 'Capacitor',
    category: 'passives',
    paletteGroup: 'capacitors',
    description: 'Electrochemical double-layer capacitor for energy buffering',
    keywords: ['supercap', 'supercapacitor', 'farad'],
  },
  {
    name: 'Power Inductor',
    anchor: 'Inductor',
    category: 'passives',
    paletteGroup: 'inductors',
    description: 'Inductor rated for DC-DC power conversion',
    keywords: ['power inductor', 'buck', 'boost', 'smps'],
  },
  {
    name: 'RF Inductor',
    anchor: 'Inductor',
    category: 'passives',
    paletteGroup: 'inductors',
    description: 'Inductor for RF matching and filtering',
    keywords: ['rf', 'coil', 'matching'],
  },
  {
    name: 'Variable Resistor',
    anchor: 'Potentiometer',
    category: 'passives',
    paletteGroup: 'potentiometers',
    description: 'Three-terminal variable resistor (rheostat / divider)',
    keywords: ['variable', 'rheostat', 'analog'],
  },
  {
    name: 'Trimmer Potentiometer',
    anchor: 'Potentiometer',
    category: 'passives',
    paletteGroup: 'potentiometers',
    description: 'Board-mount trimmer pot for calibration',
    keywords: ['trimmer', 'trimpot', '3296'],
  },
  {
    name: 'NTC Thermistor',
    anchor: 'Resistor',
    category: 'passives',
    paletteGroup: 'resistors',
    kicadSymbol: 'Device/Thermistor.kicad_sym',
    description: 'Negative temperature coefficient thermistor',
    keywords: ['ntc', 'thermistor', 'temperature'],
  },
  {
    name: 'PTC Thermistor',
    anchor: 'Resistor',
    category: 'passives',
    paletteGroup: 'resistors',
    kicadSymbol: 'Device/Thermistor.kicad_sym',
    description: 'Positive temperature coefficient thermistor',
    keywords: ['ptc', 'thermistor', 'resettable'],
  },
  {
    name: 'Ferrite Bead',
    anchor: 'Resistor',
    category: 'passives',
    paletteGroup: 'inductors',
    kicadSymbol: 'Device/L.kicad_sym',
    description: 'Ferrite bead for high-frequency noise suppression',
    keywords: ['ferrite', 'bead', 'emi', 'noise'],
  },
  {
    name: 'Fuse',
    anchor: 'Resistor',
    category: 'passives',
    paletteGroup: 'resistors',
    description: 'One-time overcurrent fuse',
    keywords: ['fuse', 'protection', 'overcurrent'],
  },
  {
    name: 'MOV (Varistor)',
    anchor: 'Resistor',
    category: 'passives',
    paletteGroup: 'resistors',
    description: 'Metal oxide varistor for surge protection',
    keywords: ['mov', 'varistor', 'surge', 'protection'],
  },
  {
    name: 'Crystal',
    anchor: 'Resistor',
    category: 'passives',
    paletteGroup: 'resistors',
    kicadSymbol: 'Device/C.kicad_sym',
    description: 'Quartz crystal resonator (two-terminal)',
    keywords: ['crystal', 'xtal', 'oscillator', 'resonator'],
  },
  {
    name: 'Photodiode',
    anchor: 'Resistor',
    category: 'sensors',
    kicadSymbol: 'Device/D.kicad_sym',
    description: 'Light-sensitive diode (simplified as resistive sensor)',
    keywords: ['photodiode', 'light', 'sensor'],
  },
  {
    name: 'Photoresistor',
    anchor: 'Resistor',
    category: 'sensors',
    kicadSymbol: 'Device/Thermistor.kicad_sym',
    description: 'Light-dependent resistor (LDR)',
    keywords: ['photoresistor', 'ldr', 'cds', 'light'],
  },
  {
    name: 'Moisture Sensor',
    anchor: 'Resistor',
    category: 'sensors',
    description: 'Resistive soil / moisture probe',
    keywords: ['moisture', 'soil', 'hydrometer', 'garden'],
  },
  {
    name: 'Rain Sensor',
    anchor: 'Resistor',
    category: 'sensors',
    description: 'Resistive rain detection pad',
    keywords: ['rain', 'weather', 'water'],
  },
]
