import type { AliasSpec } from '../core/aliasTypes'

/** LiPo max voltage ≈ 4.2 V × cell count */
const ESC_SPECS: Array<{ name: string; amps: number; cells: number; keywords: string[] }> = [
  { name: '20A 2S ESC', amps: 20, cells: 2, keywords: ['20a', '2s', '7.4v', 'small esc'] },
  { name: '30A 3S ESC', amps: 30, cells: 3, keywords: ['30a', '3s', '11.1v', 'mini quad'] },
  { name: '40A 4S ESC', amps: 40, cells: 4, keywords: ['40a', '4s', '14.8v', '450 class'] },
  { name: '50A 4S ESC', amps: 50, cells: 4, keywords: ['50a', '4s', '14.8v'] },
  { name: '60A 6S ESC', amps: 60, cells: 6, keywords: ['60a', '6s', '22.2v', '5 inch'] },
  { name: '80A 6S ESC', amps: 80, cells: 6, keywords: ['80a', '6s', '22.2v', 'freestyle'] },
  { name: '100A 8S ESC', amps: 100, cells: 8, keywords: ['100a', '8s', '29.6v'] },
  { name: '120A 12S ESC', amps: 120, cells: 12, keywords: ['120a', '12s', '50.4v', 'large drone'] },
]

function escAlias(spec: (typeof ESC_SPECS)[number]): AliasSpec {
  const maxVoltage = Math.round(spec.cells * 4.2 * 10) / 10
  return {
    name: spec.name,
    anchor: 'EscDriver',
    category: 'drivers',
    paletteGroup: 'esc',
    description: `${spec.amps} A continuous, ${spec.cells}S LiPo (up to ${maxVoltage} V) BLDC ESC`,
    keywords: spec.keywords,
  }
}

export const driverAliases: AliasSpec[] = [
  {
    name: 'A4988 Stepper Driver',
    anchor: 'StepperDriver',
    category: 'drivers',
    paletteGroup: 'stepper',
    description: 'Pololu A4988 stepper driver (STEP/DIR/EN)',
    keywords: ['a4988', 'stepper', 'pololu', 'reprap'],
  },
  {
    name: 'DRV8825 Stepper Driver',
    anchor: 'StepperDriver',
    category: 'drivers',
    paletteGroup: 'stepper',
    description: 'TI DRV8825 stepper driver module',
    keywords: ['drv8825', 'stepper', '1/32 microstep'],
  },
  {
    name: 'TMC2208 Stepper Driver',
    anchor: 'StepperDriver',
    category: 'drivers',
    paletteGroup: 'stepper',
    description: 'Trinamic TMC2208 silent stepper driver',
    keywords: ['tmc2208', 'trinamic', 'stealthchop'],
  },
  {
    name: 'L298N Motor Driver',
    anchor: 'BrushedDriver',
    category: 'drivers',
    paletteGroup: 'brushed',
    description: 'Classic L298N dual H-bridge (use one channel for brushed DC)',
    keywords: ['l298', 'l298n', 'dual h-bridge'],
  },
  {
    name: 'DRV8833 Motor Driver',
    anchor: 'BrushedDriver',
    category: 'drivers',
    paletteGroup: 'brushed',
    description: 'Low-voltage DRV8833 dual H-bridge',
    keywords: ['drv8833', '3.3v motor', 'h-bridge'],
  },
  {
    name: 'TB6612 Motor Driver',
    anchor: 'BrushedDriver',
    category: 'drivers',
    paletteGroup: 'brushed',
    description: 'TB6612FNG compact dual H-bridge',
    keywords: ['tb6612', 'tb6612fng', 'h-bridge'],
  },
  ...ESC_SPECS.map(escAlias),
  {
    name: 'PWM LED Driver',
    anchor: 'LEDDriver',
    category: 'drivers',
    paletteGroup: 'led',
    description: 'PWM dimming LED channel driver',
    keywords: ['pwm led', 'dimmer', 'mosfet led'],
  },
  {
    name: 'Constant Current LED Driver',
    anchor: 'LEDDriver',
    category: 'drivers',
    paletteGroup: 'led',
    description: 'Constant-current LED string driver',
    keywords: ['constant current', 'led strip', 'buck led'],
  },
  {
    name: 'SSD1306 OLED Driver',
    anchor: 'DisplayDriver',
    category: 'drivers',
    paletteGroup: 'display',
    kicadSymbol: 'Device/C.kicad_sym',
    description: '128×64 I2C OLED controller block',
    keywords: ['ssd1306', 'oled', '128x64', 'i2c display'],
  },
  {
    name: 'ILI9341 TFT Driver',
    anchor: 'DisplayDriver',
    category: 'drivers',
    paletteGroup: 'display',
    kicadSymbol: 'Device/C.kicad_sym',
    description: 'SPI TFT display controller block',
    keywords: ['ili9341', 'tft', 'spi display', '240x320'],
  },
  {
    name: 'HD44780 LCD Driver',
    anchor: 'DisplayDriver',
    category: 'drivers',
    paletteGroup: 'display',
    kicadSymbol: 'Device/C.kicad_sym',
    description: 'Parallel character LCD controller block',
    keywords: ['hd44780', '16x2 lcd', 'parallel lcd'],
  },
  {
    name: 'Relay Driver Module',
    anchor: 'RelayDriver',
    category: 'drivers',
    paletteGroup: 'relay',
    description: 'Low-side switch for relay coil',
    keywords: ['relay module', '1-channel relay', 'optocoupler relay'],
  },
  {
    name: 'ULN2003 Driver',
    anchor: 'RelayDriver',
    category: 'drivers',
    paletteGroup: 'relay',
    kicadSymbol: 'Device/Q_NPN.kicad_sym',
    description: 'Darlington array for relays and solenoids',
    keywords: ['uln2003', 'darlington', 'solenoid', 'relay array'],
  },
  {
    name: 'Solenoid Driver',
    anchor: 'RelayDriver',
    category: 'drivers',
    paletteGroup: 'relay',
    description: 'High-current solenoid / valve driver',
    keywords: ['solenoid', 'valve', 'actuator driver'],
  },
  {
    name: 'Class-D Audio Amplifier',
    anchor: 'AudioDriver',
    category: 'drivers',
    paletteGroup: 'audio',
    description: 'Efficient class-D speaker amplifier',
    keywords: ['class d', 'pam8403', 'audio amp'],
  },
  {
    name: 'LM386 Audio Amplifier',
    anchor: 'AudioDriver',
    category: 'drivers',
    paletteGroup: 'audio',
    kicadSymbol: 'Amplifier_Operational/LM358.kicad_sym',
    description: 'Classic LM386 low-power audio amp',
    keywords: ['lm386', 'audio', 'speaker amplifier'],
  },
  {
    name: 'LDO Regulator Driver',
    anchor: 'PowerDriver',
    category: 'drivers',
    paletteGroup: 'power',
    description: 'Linear dropout regulator block',
    keywords: ['ldo', 'ams1117', '1117-3.3', 'linear regulator'],
  },
  {
    name: 'Buck Converter Driver',
    anchor: 'PowerDriver',
    category: 'drivers',
    paletteGroup: 'power',
    description: 'Step-down switching regulator block',
    keywords: ['buck', 'step down', 'lm2596', 'dc-dc'],
  },
  {
    name: 'CP2102 USB-Serial Driver',
    anchor: 'SerialDriver',
    category: 'drivers',
    paletteGroup: 'communication',
    description: 'Silicon Labs CP2102 USB-UART bridge',
    keywords: ['cp2102', 'usb uart', 'serial adapter'],
  },
  {
    name: 'CH340 USB-Serial Driver',
    anchor: 'SerialDriver',
    category: 'drivers',
    paletteGroup: 'communication',
    description: 'CH340G USB-UART bridge',
    keywords: ['ch340', 'ch340g', 'usb serial'],
  },
  {
    name: 'Logic Level Shifter',
    anchor: 'SerialDriver',
    category: 'drivers',
    paletteGroup: 'communication',
    description: 'Bidirectional 3.3 V ↔ 5 V level shifter block',
    keywords: ['level shifter', 'logic converter', '3.3v 5v', 'txs0108'],
  },
]
