import type { AliasSpec } from '../core/aliasTypes'

export const wirelessAliases: AliasSpec[] = [
  {
    name: 'PCB Antenna',
    anchor: 'Antenna',
    category: 'wireless',
    paletteGroup: 'antennas',
    description: 'On-board 2.4 GHz PCB trace antenna',
    keywords: ['pcb antenna', '2.4ghz', 'wifi', 'ble', 'chip antenna'],
  },
  {
    name: 'Whip Antenna',
    anchor: 'Antenna',
    category: 'wireless',
    paletteGroup: 'antennas',
    description: 'External whip / monopole antenna',
    keywords: ['whip', 'monopole', 'rubber duck', '915mhz', '433mhz'],
  },
  {
    name: 'Dipole Antenna',
    anchor: 'Antenna',
    category: 'wireless',
    paletteGroup: 'antennas',
    description: 'Half-wave dipole antenna element',
    keywords: ['dipole', 'half wave', '2.4ghz dipole'],
  },
  {
    name: 'LoRa Antenna',
    anchor: 'Antenna',
    category: 'wireless',
    paletteGroup: 'antennas',
    description: 'Sub-GHz LoRa / ISM band antenna',
    keywords: ['lora', '868mhz', '915mhz', '433mhz', 'ism'],
  },
  {
    name: 'WiFi Antenna',
    anchor: 'Antenna',
    category: 'wireless',
    paletteGroup: 'antennas',
    description: '2.4 / 5 GHz WiFi antenna',
    keywords: ['wifi', 'wlan', '2.4ghz', '5ghz'],
  },
  {
    name: 'SMA Antenna',
    anchor: 'Antenna',
    category: 'wireless',
    paletteGroup: 'antennas',
    description: 'SMA connectorized antenna or pigtail',
    keywords: ['sma', 'coax', 'rf connector', 'pigtail'],
  },
  {
    name: 'U.FL Antenna Port',
    anchor: 'Antenna',
    category: 'wireless',
    paletteGroup: 'antennas',
    description: 'U.FL / IPEX coax antenna jack',
    keywords: ['u.fl', 'ipex', 'mhf4', 'coax jack'],
  },
  {
    name: 'HC-05 Bluetooth Module',
    anchor: 'BluetoothModule',
    category: 'wireless',
    paletteGroup: 'bluetooth',
    description: 'Classic Bluetooth 2.0 serial module (SPP)',
    keywords: ['hc-05', 'hc05', 'bluetooth classic', 'spp', 'uart'],
  },
  {
    name: 'HC-06 Bluetooth Module',
    anchor: 'BluetoothModule',
    category: 'wireless',
    paletteGroup: 'bluetooth',
    description: 'Slave-only Bluetooth 2.0 serial module',
    keywords: ['hc-06', 'hc06', 'bluetooth slave'],
  },
  {
    name: 'HM-10 BLE Module',
    anchor: 'BluetoothModule',
    category: 'wireless',
    paletteGroup: 'bluetooth',
    description: 'CC2541-based BLE UART module',
    keywords: ['hm-10', 'hm10', 'ble', 'cc2541', 'bluetooth low energy'],
  },
  {
    name: 'RN42 Bluetooth Module',
    anchor: 'BluetoothModule',
    category: 'wireless',
    paletteGroup: 'bluetooth',
    description: 'Microchip RN42 Class 2 Bluetooth module',
    keywords: ['rn42', 'microchip', 'bluetooth module'],
  },
  {
    name: 'nRF52840 BLE Module',
    anchor: 'BluetoothModule',
    category: 'wireless',
    paletteGroup: 'bluetooth',
    description: 'Nordic nRF52840 BLE SoC module',
    keywords: ['nrf52840', 'nordic', 'ble', 'bluetooth 5'],
  },
]
