import type { AliasSpec } from '../core/aliasTypes'

export const icAliases: AliasSpec[] = [
  {
    name: 'LM317M',
    anchor: 'LinearRegulator',
    category: 'ics',
    paletteGroup: 'regulators',
    kicadSymbol: 'Regulator_Linear/LM317.kicad_sym',
    description: 'LM317M adjustable 1.25–37 V linear regulator, 1.5 A (TO-252 / SOT-223)',
    keywords: ['lm317', 'lm317m', 'adjustable regulator', 'linear regulator', 'to-252'],
  },
  {
    name: 'AMS1117-3.3',
    anchor: 'FixedRegulator',
    category: 'ics',
    paletteGroup: 'regulators',
    kicadSymbol: 'Regulator_Linear/AP1117-33.kicad_sym',
    description: 'AMS1117 3.3 V fixed LDO, 1 A, low dropout',
    keywords: ['ams1117', '1117-3.3', '3.3v ldo', 'sot-223'],
    propertyDefaults: { outputVoltage: 3.3, dropout: 1.1, maxCurrent: 1 },
  },
  {
    name: 'AMS1117-5.0',
    anchor: 'FixedRegulator',
    category: 'ics',
    paletteGroup: 'regulators',
    kicadSymbol: 'Regulator_Linear/AP1117-50.kicad_sym',
    description: 'AMS1117 5 V fixed LDO, 1 A, low dropout',
    keywords: ['ams1117', '1117-5', '5v ldo', 'sot-223'],
    propertyDefaults: { outputVoltage: 5, dropout: 1.1, maxCurrent: 1 },
  },
  {
    name: 'LM1117-3.3',
    anchor: 'FixedRegulator',
    category: 'ics',
    paletteGroup: 'regulators',
    kicadSymbol: 'Regulator_Linear/AP1117-33.kicad_sym',
    description: 'LM1117 3.3 V fixed LDO, 800 mA',
    keywords: ['lm1117', '1117-3.3', '3.3v regulator'],
    propertyDefaults: { outputVoltage: 3.3, dropout: 1.2, maxCurrent: 0.8 },
  },
  {
    name: 'LM1117-5.0',
    anchor: 'FixedRegulator',
    category: 'ics',
    paletteGroup: 'regulators',
    kicadSymbol: 'Regulator_Linear/AP1117-50.kicad_sym',
    description: 'LM1117 5 V fixed LDO, 800 mA',
    keywords: ['lm1117', '1117-5', '5v regulator'],
    propertyDefaults: { outputVoltage: 5, dropout: 1.2, maxCurrent: 0.8 },
  },
  {
    name: 'LM7805',
    anchor: 'FixedRegulator',
    category: 'ics',
    paletteGroup: 'regulators',
    kicadSymbol: 'Regulator_Linear/L7805.kicad_sym',
    description: 'LM7805 5 V fixed linear regulator, 1 A (TO-220)',
    keywords: ['7805', 'lm7805', '5v regulator', 'to-220'],
    propertyDefaults: { outputVoltage: 5, dropout: 2, maxCurrent: 1 },
  },
  {
    name: 'LM7809',
    anchor: 'FixedRegulator',
    category: 'ics',
    paletteGroup: 'regulators',
    kicadSymbol: 'Regulator_Linear/L7809.kicad_sym',
    description: 'LM7809 9 V fixed linear regulator, 1 A (TO-220)',
    keywords: ['7809', 'lm7809', '9v regulator', 'to-220'],
    propertyDefaults: { outputVoltage: 9, dropout: 2, maxCurrent: 1 },
  },
  {
    name: 'LM7812',
    anchor: 'FixedRegulator',
    category: 'ics',
    paletteGroup: 'regulators',
    kicadSymbol: 'Regulator_Linear/L7812.kicad_sym',
    description: 'LM7812 12 V fixed linear regulator, 1 A (TO-220)',
    keywords: ['7812', 'lm7812', '12v regulator', 'to-220'],
    propertyDefaults: { outputVoltage: 12, dropout: 2, maxCurrent: 1 },
  },
  {
    name: 'AP2112K-3.3',
    anchor: 'FixedRegulator',
    category: 'ics',
    paletteGroup: 'regulators',
    description: 'AP2112K 3.3 V ultra-low-dropout regulator, 600 mA (SOT-23-5)',
    keywords: ['ap2112', 'uldo', '3.3v ldo', 'sot-23'],
    propertyDefaults: { outputVoltage: 3.3, dropout: 0.4, maxCurrent: 0.6 },
  },
]
