import type { AliasSpec } from '../core/aliasTypes'

export const semiconductorAliases: AliasSpec[] = [
  {
    name: 'Rectifier Diode',
    anchor: 'Diode',
    category: 'semiconductors',
    paletteGroup: 'diodes',
    description: 'Standard silicon rectifier diode (e.g. 1N4007)',
    keywords: ['rectifier', '1n4007', '1n5819'],
  },
  {
    name: 'Small Signal Diode',
    anchor: 'Diode',
    category: 'semiconductors',
    paletteGroup: 'diodes',
    description: 'Low-current signal switching diode (e.g. 1N4148)',
    keywords: ['signal', '1n4148', 'switching'],
  },
  {
    name: 'Fast Recovery Diode',
    anchor: 'Diode',
    category: 'semiconductors',
    paletteGroup: 'diodes',
    description: 'Fast recovery rectifier for switching supplies',
    keywords: ['fast recovery', 'frd', 'switching'],
  },
  {
    name: 'Schottky Diode',
    anchor: 'Diode',
    category: 'semiconductors',
    paletteGroup: 'diodes',
    description: 'Low forward-voltage Schottky rectifier',
    keywords: ['schottky', '1n5819', 'ss14'],
  },
  {
    name: 'ESD Protection Diode',
    anchor: 'Diode',
    category: 'semiconductors',
    paletteGroup: 'diodes',
    description: 'ESD clamp diode for signal-line protection',
    keywords: ['esd', 'tvs', 'protection', 'clamp'],
  },
  {
    name: 'Reverse Polarity Protection',
    anchor: 'Diode',
    category: 'semiconductors',
    paletteGroup: 'diodes',
    description: 'Series Schottky for reverse-polarity protection',
    keywords: ['reverse polarity', 'protection', 'schottky'],
  },
  {
    name: 'TVS Diode',
    anchor: 'ZenerDiode',
    category: 'semiconductors',
    paletteGroup: 'diodes',
    description: 'Transient voltage suppression diode',
    keywords: ['tvs', 'transient', 'esd', 'surge'],
  },
  {
    name: 'TVS',
    anchor: 'ZenerDiode',
    category: 'semiconductors',
    paletteGroup: 'diodes',
    description: 'Transient voltage suppressor (TVS)',
    keywords: ['tvs', 'transient', 'clamp'],
  },
  {
    name: 'Darlington Pair',
    anchor: 'NPNTransistor',
    category: 'semiconductors',
    paletteGroup: 'transistors',
    description: 'Darlington NPN transistor pair for high gain',
    keywords: ['darlington', 'tip120', 'ulN2003'],
  },
  {
    name: 'Phototransistor',
    anchor: 'NPNTransistor',
    category: 'semiconductors',
    paletteGroup: 'transistors',
    description: 'Light-activated NPN phototransistor',
    keywords: ['phototransistor', 'optical', 'sensor'],
  },
  {
    name: '2N3906 PNP Transistor',
    anchor: 'PNPTransistor',
    category: 'semiconductors',
    paletteGroup: 'transistors',
    description: 'General-purpose PNP BJT (2N3906)',
    keywords: ['2n3906', 'pnp', 'transistor'],
  },
  {
    name: 'IRF9540 P-Channel MOSFET',
    anchor: 'PMOSFET',
    category: 'semiconductors',
    paletteGroup: 'transistors',
    description: 'P-channel power MOSFET (IRF9540)',
    keywords: ['irf9540', 'pmos', 'p-channel', 'high-side'],
  },
  {
    name: 'Buffer Amplifier',
    anchor: 'OpAmp',
    category: 'semiconductors',
    description: 'Unity-gain op-amp voltage buffer',
    keywords: ['buffer', 'follower', 'unity gain'],
  },
]
